### ISSUE TITLE
Cross uses host cargo config.toml

### ISSUE THREAD

**Issue by DizzyWasTaken** [rust-embedded/cross#622] opened 2022-01-03 02:54 UTC
Hello,

I'm building with cross using a custom docker image and it uses my host `.cargo/config.toml` parameters. In particular
```
[build]
rustc-wrapper = "sccache"
```
which makes every attempt at building fail.

I was under the impression that the rust environment cross uses was the one that's on the docker image. Is there a way of making it ignore my host's cargo config?

**Comment by Emilgardis** [comment] 2022-01-05 07:33
Duplicate of #621

**Closed by Emilgardis** 2022-01-05 07:33 UTC

**Comment by DizzyWasTaken** [comment] 2022-01-06 22:19
Oops, didn't notice. Thanks for the notice.
